//! Development-grade FDM/FOQA-style event detection.
//!
//! IMPORTANT: these are DEVELOPMENT thresholds for testing the analysis
//! pipeline headlessly. They are NOT airline policy, not FOQA-certified
//! limits, and not real A320 performance data. Thresholds are named and
//! configurable so future aircraft/operator packages can override them.
//!
//! Rules consume consecutive FDR samples of generic core fields. Fields that
//! are unknown produce NO events (never fabricated).

use crate::fdr::FdrSample;
use serde::{Deserialize, Serialize};

/// Development threshold set (`ApproachProfile::DevelopmentDefault`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DevelopmentThresholds {
    /// Excessive sink rate below this AGL (ft), |VS| above this (fpm).
    pub excessive_sink_rate_fpm: f64,
    pub excessive_sink_max_agl_ft: f64,
    /// Excessive bank below this AGL (ft), bank above this (deg).
    pub excessive_bank_deg: f64,
    pub excessive_bank_max_agl_ft: f64,
    /// Hard touchdown: vertical speed at touchdown beyond this (|fpm|).
    pub hard_touchdown_vs_fpm: f64,
}

impl Default for DevelopmentThresholds {
    fn default() -> Self {
        // DEVELOPMENT DEFAULTS — not airline policy.
        Self {
            excessive_sink_rate_fpm: 1200.0,
            excessive_sink_max_agl_ft: 2500.0,
            excessive_bank_deg: 30.0,
            excessive_bank_max_agl_ft: 1500.0,
            hard_touchdown_vs_fpm: 600.0,
        }
    }
}

/// One detected FDM event.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FdmEvent {
    pub sample_seq: u64,
    pub timestamp_ms: u64,
    pub kind: FdmEventKind,
    pub measured: f64,
    pub threshold: f64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FdmEventKind {
    ExcessiveSinkRate,
    ExcessiveBankLowAltitude,
    HardTouchdown,
}

/// Stateful analyzer over an ordered sample stream.
#[derive(Debug)]
pub struct FdmAnalyzer {
    thresholds: DevelopmentThresholds,
    prev_on_ground: Option<bool>,
    events: Vec<FdmEvent>,
}

impl FdmAnalyzer {
    pub fn new(thresholds: DevelopmentThresholds) -> Self {
        Self {
            thresholds,
            prev_on_ground: None,
            events: Vec::new(),
        }
    }

    pub fn new_development_default() -> Self {
        Self::new(DevelopmentThresholds::default())
    }

    pub fn events(&self) -> &[FdmEvent] {
        &self.events
    }

    pub fn into_events(self) -> Vec<FdmEvent> {
        self.events
    }

    /// Feed one ordered FDR sample; returns events generated by it.
    pub fn process(&mut self, s: &FdrSample) -> Vec<FdmEvent> {
        let mut new_events = Vec::new();

        // Excessive sink rate (airborne only, known AGL + VS).
        if !matches!(s.on_ground, Some(true))
            && let (Some(agl), Some(vs)) = (s.radio_altitude, s.vertical_speed)
            && agl <= self.thresholds.excessive_sink_max_agl_ft
            && vs.is_finite()
            && -vs >= self.thresholds.excessive_sink_rate_fpm
        {
            new_events.push(FdmEvent {
                sample_seq: s.seq,
                timestamp_ms: s.timestamp.ms,
                kind: FdmEventKind::ExcessiveSinkRate,
                measured: -vs,
                threshold: self.thresholds.excessive_sink_rate_fpm,
            });
        }

        // Excessive bank at low altitude.
        if !matches!(s.on_ground, Some(true))
            && let (Some(agl), Some(bank)) = (s.radio_altitude, s.bank)
            && agl <= self.thresholds.excessive_bank_max_agl_ft
            && bank.is_finite()
            && bank.abs() >= self.thresholds.excessive_bank_deg
        {
            new_events.push(FdmEvent {
                sample_seq: s.seq,
                timestamp_ms: s.timestamp.ms,
                kind: FdmEventKind::ExcessiveBankLowAltitude,
                measured: bank.abs(),
                threshold: self.thresholds.excessive_bank_deg,
            });
        }

        // Touchdown transition: airborne -> on_ground with known VS.
        if let (Some(prev_g), Some(now_g)) = (self.prev_on_ground, s.on_ground)
            && !prev_g
            && now_g
            && let Some(vs) = s.vertical_speed
            && vs.is_finite()
        {
            let impact = -vs;
            if impact >= self.thresholds.hard_touchdown_vs_fpm {
                new_events.push(FdmEvent {
                    sample_seq: s.seq,
                    timestamp_ms: s.timestamp.ms,
                    kind: FdmEventKind::HardTouchdown,
                    measured: impact,
                    threshold: self.thresholds.hard_touchdown_vs_fpm,
                });
            }
        }

        self.prev_on_ground = s.on_ground;
        self.events.extend(new_events.iter().cloned());
        new_events
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::fdr::Recorder;
    use fd_core::telemetry::{SimState, SimTimestamp, TelemetrySnapshot};
    use fd_core::units::{AltitudeAglFt, AltitudeFt, AngleDeg, VerticalSpeedFpm};

    fn analyzer() -> FdmAnalyzer {
        FdmAnalyzer::new(DevelopmentThresholds {
            excessive_sink_rate_fpm: 1000.0,
            excessive_sink_max_agl_ft: 2000.0,
            excessive_bank_deg: 30.0,
            excessive_bank_max_agl_ft: 1000.0,
            hard_touchdown_vs_fpm: 500.0,
        })
    }

    fn sample(
        rec: &mut Recorder,
        seq: u64,
        agl: Option<f64>,
        vs: Option<f64>,
        bank: Option<f64>,
        on_ground: Option<bool>,
    ) -> FdrSample {
        let mut snap = TelemetrySnapshot::empty(SimTimestamp::new(seq * 100));
        snap.altitude_agl = agl.map(AltitudeAglFt::new);
        snap.altitude_msl = agl.map(|a| AltitudeFt::new(a + 100.0));
        snap.vertical_speed = vs.map(VerticalSpeedFpm::new);
        snap.bank = bank.map(AngleDeg::new);
        snap.on_ground = on_ground;
        snap.sim_timing.state = SimState::Running;
        rec.record(&snap, "TEST")
    }

    #[test]
    fn normal_stream_produces_no_false_events() {
        let mut a = analyzer();
        let mut rec = Recorder::new();
        for i in 0..6 {
            let s = sample(
                &mut rec,
                i,
                Some(3000.0 - (i as f64) * 400.0),
                Some(-700.0),
                Some(8.0),
                Some(false),
            );
            assert!(a.process(&s).is_empty(), "false positive at sample {i}");
        }
    }

    #[test]
    fn excessive_sink_produces_event() {
        let mut a = analyzer();
        let mut rec = Recorder::new();
        let s = sample(
            &mut rec,
            1,
            Some(800.0),
            Some(-1400.0),
            Some(0.0),
            Some(false),
        );
        let evts = a.process(&s);
        assert_eq!(evts.len(), 1);
        assert_eq!(evts[0].kind, FdmEventKind::ExcessiveSinkRate);
        assert!((evts[0].measured - 1400.0).abs() < 1e-9);
    }

    #[test]
    fn low_altitude_excessive_bank_produces_event() {
        let mut a = analyzer();
        let mut rec = Recorder::new();
        let s = sample(
            &mut rec,
            2,
            Some(400.0),
            Some(-200.0),
            Some(-35.0),
            Some(false),
        );
        let evts = a.process(&s);
        assert_eq!(evts.len(), 1);
        assert_eq!(evts[0].kind, FdmEventKind::ExcessiveBankLowAltitude);
    }

    #[test]
    fn unknown_measurements_never_fabricate_events() {
        let mut a = analyzer();
        let mut rec = Recorder::new();
        // AGL / VS / bank all unknown.
        let s = sample(&mut rec, 3, None, None, None, Some(false));
        assert!(a.process(&s).is_empty());
    }

    #[test]
    fn touchdown_transition_is_detected_with_vs() {
        let mut a = analyzer();
        let mut rec = Recorder::new();
        let airborne = sample(&mut rec, 1, Some(5.0), Some(-120.0), Some(0.0), Some(false));
        a.process(&airborne);
        let touchdown = sample(&mut rec, 2, Some(0.0), Some(-150.0), Some(0.0), Some(true));
        let evts = a.process(&touchdown);
        // Soft touchdown (< 500 fpm dev threshold): no FDM event, but the
        // transition itself is observable via QoL (tested there).
        assert!(evts.is_empty());
    }

    #[test]
    fn hard_touchdown_produces_event() {
        let mut a = analyzer();
        let mut rec = Recorder::new();
        let airborne = sample(&mut rec, 1, Some(5.0), Some(-600.0), Some(0.0), Some(false));
        a.process(&airborne);
        let touchdown = sample(&mut rec, 2, Some(0.0), Some(-650.0), Some(0.0), Some(true));
        let evts = a.process(&touchdown);
        assert_eq!(evts.len(), 1);
        assert_eq!(evts[0].kind, FdmEventKind::HardTouchdown);
    }
}
